#!/usr/bin/env python3
"""Estimate interaction time from Claude Code session transcripts.

Reads ~/.claude/projects/*/*.jsonl and reports, per day and per project:

  attention   your time at the keyboard (low/high estimate)
  wall        session wall-clock (includes agents working unattended)
  msgs        messages you actually typed
  commits     optional, from --repo

Usage
  session_hours.py --since 2026-08-11 --match tourcaddie
  session_hours.py --since 2026-08-01 --until 2026-08-15 --match kalogon --json
  session_hours.py --since 2026-08-11 \
      --label ios=-tourcaddie-ios --label android=-tourcaddie-android \
      --repo ios=~/Projects/Foo/tourcaddie-ios

See references/method.md in this skill for what the numbers mean.
"""

import argparse
import glob
import json
import os
import re
import subprocess
import sys
from bisect import bisect_left
from collections import defaultdict
from datetime import datetime, timedelta

PROJECTS_ROOT = os.path.expanduser("~/.claude/projects")

# Content prefixes that are NOT the user typing: agent notifications, slash-command
# echoes, hook/system injections, shell output. `<bash-input>` IS the user typing.
NOT_TYPED = (
    "<task-notification",
    "<local-command",
    "<command-name",
    "<command-message",
    "<command-args",
    "<bash-stdout",
    "<bash-stderr",
    "<system-reminder",
    "<user-prompt-submit-hook",
    "Caveat: The messages below were generated by the user",
)


# ---------------------------------------------------------------- transcripts


def parse_ts(raw):
    """ISO-8601 UTC string from a transcript -> local-time datetime."""
    return datetime.fromisoformat(raw.replace("Z", "+00:00")).astimezone()


def typed_text(obj):
    """Return the text of a message the user actually typed, else None."""
    if obj.get("type") != "user" or obj.get("isMeta") or obj.get("isSidechain"):
        return None
    content = obj.get("message", {}).get("content")
    if isinstance(content, list):
        content = " ".join(
            b.get("text", "")
            for b in content
            if isinstance(b, dict) and b.get("type") == "text"
        )
    if not isinstance(content, str) or not content.strip():
        return None
    text = " ".join(content.split())
    return None if text.startswith(NOT_TYPED) else text


def scan(project_dir, since, until):
    """-> (all event times, typed [(t, text)], assistant reply times)."""
    events, typed, replies = set(), {}, set()
    for path in glob.glob(os.path.join(project_dir, "*.jsonl")):
        with open(path, "r", errors="replace") as fh:
            for line in fh:
                if '"timestamp"' not in line:
                    continue
                try:
                    obj = json.loads(line)
                except ValueError:
                    continue
                raw = obj.get("timestamp")
                if not raw:
                    continue
                try:
                    when = parse_ts(raw).replace(microsecond=0)
                except ValueError:
                    continue
                if not (since <= when < until):
                    continue
                events.add(when)
                if obj.get("type") == "assistant" and not obj.get("isSidechain"):
                    replies.add(when)
                text = typed_text(obj)
                if text:
                    # resumed/forked sessions duplicate lines across files; key
                    # on the timestamp so each message is counted once
                    typed[when] = text
    return sorted(events), sorted(typed.items()), sorted(replies)


# ------------------------------------------------------------------ intervals


def merge(intervals):
    """Union of [start, end) intervals, so overlapping windows aren't double-counted."""
    out = []
    for start, end in sorted(intervals):
        if end <= start:
            continue
        if out and start <= out[-1][1]:
            out[-1][1] = max(out[-1][1], end)
        else:
            out.append([start, end])
    return out


def per_day(intervals):
    """Sum merged intervals into {date: timedelta}, splitting across midnight."""
    days = defaultdict(timedelta)
    for start, end in merge(intervals):
        cursor = start
        while cursor < end:
            midnight = cursor.replace(
                hour=0, minute=0, second=0, microsecond=0
            ) + timedelta(days=1)
            stop = min(end, midnight)
            days[cursor.date()] += stop - cursor
            cursor = stop
    return dict(days)


def wall_intervals(events, break_after):
    """Session wall-clock: consecutive events, gaps over `break_after` end a block."""
    if not events:
        return []
    blocks, start, prev = [], events[0], events[0]
    for when in events[1:]:
        if when - prev > break_after:
            blocks.append([start, prev])
            start = when
        prev = when
    blocks.append([start, prev])
    return blocks


def attention_intervals(typed, replies, cap, watch):
    """Your time: read-and-compose before each message you sent, plus a watch window.

    The gap since the previous assistant reply is read-and-compose time, capped
    (the cap is what excludes the walked-away tail). The watch window is time
    spent reading the response you just triggered.
    """
    floor = timedelta(seconds=20)
    out = []
    for when, _ in typed:
        i = bisect_left(replies, when) - 1
        read = min(when - replies[i], cap) if i >= 0 else timedelta(minutes=1)
        out.append([when - max(read, floor), when + watch])
    return out


# ----------------------------------------------------------------------- git


def commits_by_day(repo, since, until):
    repo = os.path.expanduser(repo)
    if not os.path.isdir(os.path.join(repo, ".git")):
        return {}, f"not a git repo: {repo}"
    try:
        out = subprocess.run(
            [
                "git", "-C", repo, "log", "--all",
                f"--since={since.isoformat()}",
                f"--until={until.isoformat()}",
                "--date=format-local:%Y-%m-%d",
                "--pretty=%ad",
            ],
            capture_output=True, text=True, timeout=60,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        return {}, f"git failed for {repo}: {exc}"
    if out.returncode != 0:
        return {}, f"git failed for {repo}: {out.stderr.strip()[:200]}"
    counts = defaultdict(int)
    for line in out.stdout.split():
        counts[datetime.strptime(line, "%Y-%m-%d").date()] += 1
    return dict(counts), None


# -------------------------------------------------------------------- output


def hm(td):
    total = int(td.total_seconds())
    return f"{total // 3600}:{total % 3600 // 60:02d}"


def round_up(td, minutes):
    """Round a duration up to the next multiple of `minutes`. Zero stays zero.

    Applied per project per day — each project is its own invoice line, so each
    gets its own rounding. A day touching three projects rounds three times.
    """
    if not minutes or td <= timedelta():
        return td
    step = minutes * 60
    secs = td.total_seconds()
    return timedelta(seconds=-(-secs // step) * step)


def resolve_projects(args):
    """-> ordered {label: directory}."""
    found = {}
    for spec in args.label or []:
        if "=" not in spec:
            sys.exit(f"--label needs LABEL=SUBSTRING, got: {spec}")
        label, needle = spec.split("=", 1)
        # a trailing "$" anchors to the end of the directory name, which is how
        # you separate a parent project from its own subdirectory projects
        anchored = needle.endswith("$")
        stem = needle[:-1] if anchored else needle
        hits = sorted(
            d for d in os.listdir(PROJECTS_ROOT)
            if (d.endswith(stem) if anchored else stem in d)
            and os.path.isdir(os.path.join(PROJECTS_ROOT, d))
        )
        if not hits:
            sys.exit(f"no project directory matches {needle!r}")
        if len(hits) > 1:
            sys.exit(
                f"{needle!r} matches {len(hits)}: {', '.join(hits)}\n"
                f"       narrow it, or anchor to the end with {stem + '$'!r}"
            )
        found[label] = os.path.join(PROJECTS_ROOT, hits[0])
    for needle in args.match or []:
        for name in sorted(os.listdir(PROJECTS_ROOT)):
            path = os.path.join(PROJECTS_ROOT, name)
            if needle in name and os.path.isdir(path) and path not in found.values():
                # -Users-me-Projects-Acme-widget-ios -> widget-ios
                label = re.sub(r"^-.*?-Projects-", "", name) or name
                found[label] = path
    if not found:
        sys.exit("no projects selected; pass --match or --label")
    return found


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--since", required=True, metavar="YYYY-MM-DD")
    ap.add_argument("--until", metavar="YYYY-MM-DD",
                    help="exclusive; defaults to tomorrow so today is included")
    ap.add_argument("--match", action="append", metavar="SUBSTR",
                    help="include every project dir containing SUBSTR (repeatable)")
    ap.add_argument("--label", action="append", metavar="LABEL=SUBSTR",
                    help="name one project explicitly (repeatable)")
    ap.add_argument("--repo", action="append", metavar="[LABEL=]PATH",
                    help="count commits from a git repo (repeatable)")
    ap.add_argument("--cap-low", type=int, default=5, metavar="MIN",
                    help="read-and-compose cap, low estimate (default 5)")
    ap.add_argument("--cap-high", type=int, default=10, metavar="MIN",
                    help="read-and-compose cap, high estimate (default 10)")
    ap.add_argument("--break-after", type=int, default=20, metavar="MIN",
                    help="gap that ends a wall-clock block (default 20)")
    ap.add_argument("--round", type=int, default=15, metavar="MIN",
                    help="round each project's daily figure up to this increment "
                         "(default 15; 0 disables and reports raw time)")
    ap.add_argument("--json", action="store_true", help="emit JSON instead of a table")
    args = ap.parse_args()

    tz = datetime.now().astimezone().tzinfo
    since = datetime.strptime(args.since, "%Y-%m-%d").replace(tzinfo=tz)
    until = (
        datetime.strptime(args.until, "%Y-%m-%d").replace(tzinfo=tz)
        if args.until
        else datetime.now(tz).replace(hour=0, minute=0, second=0, microsecond=0)
        + timedelta(days=1)
    )
    if until <= since:
        sys.exit("--until must be after --since")

    projects = resolve_projects(args)
    cap_lo, cap_hi = timedelta(minutes=args.cap_low), timedelta(minutes=args.cap_high)
    brk = timedelta(minutes=args.break_after)
    warnings = []

    data, spans = {}, {}
    for label, path in projects.items():
        events, typed, replies = scan(path, since, until)
        lo = attention_intervals(typed, replies, cap_lo, timedelta(minutes=1))
        hi = attention_intervals(typed, replies, cap_hi, timedelta(minutes=2))
        msgs = defaultdict(int)
        for when, _ in typed:
            msgs[when.date()] += 1
        data[label] = {
            "lo": per_day(lo),
            "hi": per_day(hi),
            "wall": per_day(wall_intervals(events, brk)),
            "msgs": dict(msgs),
            "commits": {},
        }
        spans[label] = (typed[0][0], typed[-1][0]) if typed else None

    for spec in args.repo or []:
        label, _, path = spec.rpartition("=")
        if not label:
            label = os.path.basename(os.path.expanduser(path).rstrip("/"))
        counts, err = commits_by_day(path, since, until)
        if err:
            warnings.append(err)
        data.setdefault(label, {"lo": {}, "hi": {}, "wall": {}, "msgs": {}, "commits": {}})
        data[label]["commits"] = counts

    labels = list(data)
    days = sorted({d for v in data.values() for k in v for d in v[k]})

    def midpoint(v, day):
        return (v["lo"].get(day, timedelta()) + v["hi"].get(day, timedelta())) / 2

    if args.json:
        print(json.dumps({
            "since": since.isoformat(), "until": until.isoformat(),
            "timezone": str(tz),
            "params": {"cap_low_min": args.cap_low, "cap_high_min": args.cap_high,
                       "break_after_min": args.break_after,
                       "round_up_min": args.round},
            "projects": {
                label: {
                    "directory": projects.get(label),
                    "days": {
                        str(d): {
                            "attention_low_min": round(v["lo"].get(d, timedelta()).total_seconds() / 60, 1),
                            "attention_high_min": round(v["hi"].get(d, timedelta()).total_seconds() / 60, 1),
                            "attention_mid_min": round(midpoint(v, d).total_seconds() / 60, 1),
                            "billable_min": round(
                                round_up(midpoint(v, d), args.round).total_seconds() / 60, 1),
                            "wall_min": round(v["wall"].get(d, timedelta()).total_seconds() / 60, 1),
                            "typed_messages": v["msgs"].get(d, 0),
                            "commits": v["commits"].get(d, 0),
                        }
                        for d in days
                        if any(v[k].get(d) for k in ("lo", "hi", "wall", "msgs", "commits"))
                    },
                }
                for label, v in data.items()
            },
            "warnings": warnings,
        }, indent=2))
        return

    span = f"{since.date()} through {(until - timedelta(days=1)).date()}  ({tz})"
    if not days:
        print(f"\nNo activity on {', '.join(labels)}")
        print(f"{span}\n")
        for w in warnings:
            print(f"warning: {w}", file=sys.stderr)
        return

    rounding = args.round
    width = max(11, max((len(l) for l in labels), default=11) + 2)
    head = f"{'Day':<12}" + "".join(f"{l:>{width}}" for l in labels)
    head += f"{'BILLABLE':>11}{'raw':>8}" if rounding else f"{'YOUR TIME':>11}"
    head += f"{'wall':>8}{'msgs':>6}{'commits':>9}"
    print(f"\nYour time on: {', '.join(labels)}")
    print(f"{span}\n")
    print(head)
    print("-" * len(head))

    blank = {"lo": timedelta(), "hi": timedelta(), "bill": timedelta(),
             "raw": timedelta(), "wall": timedelta(), "msgs": 0, "commits": 0}
    tot = {l: dict(blank) for l in labels}
    grand = dict(blank)

    for day in days:
        row = f"{day.strftime('%a %b %d'):<12}"
        d = dict(blank)
        for label in labels:
            v = data[label]
            raw = midpoint(v, day)
            cell = {
                "lo": v["lo"].get(day, timedelta()),
                "hi": v["hi"].get(day, timedelta()),
                "raw": raw,
                "bill": round_up(raw, rounding),
                "wall": v["wall"].get(day, timedelta()),
                "msgs": v["msgs"].get(day, 0),
                "commits": v["commits"].get(day, 0),
            }
            for key, val in cell.items():
                tot[label][key] += val
                d[key] += val
            shown = hm(cell["bill"]) if cell["bill"] else "-"
            row += f"{shown:>{width}}"
        row += f"{hm(d['bill']):>11}{hm(d['raw']):>8}" if rounding else f"{hm(d['raw']):>11}"
        row += f"{hm(d['wall']):>8}{d['msgs']:>6}{d['commits']:>9}"
        for key in grand:
            grand[key] += d[key]
        print(row)

    print("-" * len(head))
    row = f"{'TOTAL':<12}" + "".join(f"{hm(tot[l]['bill']):>{width}}" for l in labels)
    row += f"{hm(grand['bill']):>11}{hm(grand['raw']):>8}" if rounding else f"{hm(grand['raw']):>11}"
    row += f"{hm(grand['wall']):>8}{grand['msgs']:>6}{grand['commits']:>9}"
    print(row)

    if rounding:
        print(f"\nBillable: {hm(grand['bill'])}  "
              f"(each project's daily figure rounded up to {rounding} min)")
        print(f"Raw estimate: {hm(grand['raw'])}  "
              f"(midpoint of {hm(grand['lo'])}-{hm(grand['hi'])}) "
              f"— rounding adds {hm(grand['bill'] - grand['raw'])}")
    else:
        print(f"\nBest estimate: {hm(grand['raw'])}  "
              f"(midpoint of {hm(grand['lo'])}-{hm(grand['hi'])})")
    if grand["raw"]:
        print(f"Session wall-clock {hm(grand['wall'])} — "
              f"{grand['wall'] / grand['raw']:.1f}x leverage over raw")

    pad = max(len(l) for l in labels)
    for label in labels:
        t = tot[label]
        extra = f", {t['commits']} commits" if t["commits"] else ""
        lead = f"{hm(t['bill']):>7} billable  {hm(t['raw']):>7} raw" if rounding \
            else f"{hm(t['raw']):>7}"
        print(f"  {label:<{pad}}  {lead}  "
              f"({hm(t['lo'])}-{hm(t['hi'])}, {t['msgs']} msgs{extra})")
    for w in warnings:
        print(f"\nwarning: {w}", file=sys.stderr)


if __name__ == "__main__":
    main()
